// <auto-generated />
namespace test_base_donnee_indemnite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nokey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nokey));
        
        string IMigrationMetadata.Id
        {
            get { return "202106171932248_nokey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
